const ILLNESS_LABELS: Record<string, string> = {
  'somatik:biriktiruvchi_toqima':
    'Biriktiruvchi toʻqima tizimli shikastlanishi, yoshlar revmatoid artriti va tugunchali periarteritning ogʻir turlari',
  'somatik:yurak_kasalligi': 'Yurak va qon aylanish tizimining tugʻma nuqsonlari (II-III daraja)',
  'somatik:tetrada_fallo': 'Ogʻir darajadagi tetrada Fallo kasalligi',
  'somatik:opka_bronx': 'Oʻpka-bronx kasalliklari (II-III darajali nafas yetishmovchiligi)',
  'somatik:asma': 'Astmaning ogʻir darajasi',
  'somatik:glom': 'Surunkali glomerulonefrit',
  'somatik:piyelonefrit': 'Surunkali piyelonefrit',
  'somatik:otkir_glom': 'Oʻtkir glomerulonefrit remissiya davri',
  'somatik:onkologiya': 'Turli organlarning xavfli oʻsmalari',
  'somatik:mukovissidoz': 'Mukovissedozning ogʻir turi',
  'somatik:seliakiya': 'Seliakiyaning ogʻir turi',
  'somatik:yarali_kolit': 'Nospetsifik yarali kolitning ogʻir turi',
  'somatik:kron': 'Kron kasalligining ogʻir darajasi',
  'somatik:jigar_sirrozi': 'Jigar sirrozining dekompensatsiya darajasi',
  'somatik:oqsil_yetishmovchiligi': 'Oqsil-energetik yetishmovchiligining ogʻir darajasi',
  'somatik:leykoz': 'Oʻtkir leykoz, aplastik va irsiy kamqonliklar',
  'somatik:gemorragik': 'Ogʻir gemorragik kriz bilan kechuvchi surunkali kasalliklar',
  'somatik:immun_tanqisligi': 'Tugʻma va orttirilgan immun tanqisligi holatlari',
  'psix:ruhiy': 'Ruhiy holati buzilganligi (shizofreniya, psixoz)',
  'psix:nevroz': 'Ogʻir nevrozlar va nevroz holatlarining zoʻraygan davri',
  'psix:ensefaloastenik': 'Ensefaloastenik holatlar',
  'psix:psixopatiya': 'Psixopatiyalar, dekompensatsiya davridagi holatlar',
  'psix:epilepsiya': 'Epilepsiyaning zoʻraygan davrida',
  'psix:harakat_buzilishi': 'Tayanch-harakat aʼzolarining buzilishi',
  'psix:serebral_falaj': 'Bolalar serebral falaji (yengil turi)',
  'psix:avtizm': 'Bolalar autizmi',
  'psix:miopatiya': 'Miopatiya / Miasteniyaning tarqalgan shakli',
  'psix:demiyelin': 'Asab tizimining demiyelinlashtiruvchi kasalliklari',
  'xir:orqa_miya': 'Orqa miya churrasi',
  'xir:siydik': 'Siydik tuta olmaslik / ekstrofiya / atoniya',
  'xir:atreziya': 'Orqa chiqaruv yoʻllarining atreziyasi',
  'xir:oyoqlar': 'Turli kasalliklarda oyoqlarning falaji',
  'xir:osteomiyelit': 'Surunkali tayanch-harakat aʼzolari kasalligi',
  'xir:bosh_miya': 'Bosh miya operatsiyasidan keyingi holatlar',
  'xir:reabilitatsiya': 'Operatsiyadan keyingi reabilitativ davr',
  'teri:epidermoliz': 'Tugʻma bullezepidermoliz',
  'teri:ihtioz': 'Tugʻma ixtiozning zoʻraygan davri',
  'teri:psoriaz_yiringli': 'Eritrodermiya psoriazining yiringli turi',
  'teri:psoriaz_artropatik': 'Artropatik psoriazi',
  'teri:teri_sil': 'Oʻtkir teri sil kasalligi',
  'uyda:1a': '1-a. Psixologik rivojlanishning aralash spetsifik buzilishlari (F83)',
  'uyda:1b': '1-b. Bolalar autizmi (F84.0)',
  'uyda:2a': '2-a. Yengil darajadagi aqliy zaiflik (F70)',
  'uyda:2b': '2-b. Mo‘tadil aqliy zaiflik (F71)',
  'uyda:3a': '3-a. Ekspressiv nutqning buzilishi (F80.1)',
  'uyda:3b': '3-b. Retseptiv nutqning buzilishi (F80.2)',
  'uyda:3v-tanglay': '3-v. Tanglay yorig‘i (Q35)',
  'uyda:3v-tanglay-lab': '3-v. Tanglay va lab yorig‘i (Q37)',
  'uyda:3v-manqalik': '3-v. Ochiq va yopiq manqalik (R49.2)',
  'uyda:3g': '3-g. O‘rtacha yoki og‘ir darajadagi duduqlik (F98.5)',
  'uyda:3d': '3-d. Dizartriya (R47.1)',
  'uyda:3e': '3-e. Bolalar afaziyasi (F80.3)',
  'uyda:4a': '4-a. Ikkala ko‘zning ko‘rligi (N54.0)',
  'uyda:4b-mikroftalm': '4-b. Mikroftalm (Q11)',
  'uyda:4b-mikrokornea': '4-b. Mikrokornea (Q13.4)',
  'uyda:4b-anoftalm': '4-b. Anoftalm (Q11)',
  'uyda:4v': '4-v. To‘r pardasining tug‘ma nuqsonlari (N33-35)',
  'uyda:4g-retinoblastoma': '4-g. Retinoblastoma (C69.2)',
  'uyda:4g-bir-koz': '4-g. Bir ko‘zning ko‘rligi (N54.1)',
  'uyda:4d': '4-d. Koloboma (Q13.0)',
  'uyda:4e': '4-e. Pretinopatiya (N35.1)',
  'uyda:4j': '4-j. Ko‘rish nervining atrofiyasi (N47.2)',
  'uyda:4z': '4-z. Ko‘rish nervi disk va makula gipoplaziyasi (Q14.2)',
  'uyda:4i': '4-i. Albinizm (E70.3)',
  'uyda:4k': '4-k. Aniridiya (Q13.1)',
  'uyda:4l-n26': '4-l. Katarakta (N26.0)',
  'uyda:4l-q12': '4-l. Katarakta (Q12.0)',
  'uyda:4m-n27': '4-m. Ko‘z gavharining boshqa kasalliklari (N27)',
  'uyda:4m-afakiya-n27': '4-m. Afakiya yoki tug‘ma afakiya (N27.0)',
  'uyda:4m-afakiya-q12': '4-m. Afakiya yoki tug‘ma afakiya (Q12.3)',
  'uyda:4n': '4-n. Ko‘z gavhari siljishi (Q12.1)',
  'uyda:4o': '4-o. Ko‘z gavharining chiqishi (N27.1)',
  'uyda:4p': '4-p. Glaukoma (N40–42)',
  'uyda:4r': '4-r. Tug‘ma miopiyaning yuqori darajasi (N52.1)',
  'uyda:4s': '4-s. Gipermetropiyaning yuqori darajasi (N52.0)',
  'uyda:4t': '4-t. Nistagm va ko‘zning beixtiyor harakatlari (N55)',
  'uyda:5a': '5-a. Otologik va audiologik implantatlar (N90.3 Z96.2)',
  'uyda:5b': '5-b. Ikki tomonlama neyrosensor karlik II darajasi (N90.3)',
  'uyda:5v': '5-v. Ikki tomonlama neyrosensor karlik III darajasi (N90.3)',
  'uyda:5g': '5-g. Ikki tomonlama neyrosensor karlik IV darajasi, protezlash (N90.3)',
  'uyda:5d': '5-d. Ikki tomonlama neyrosensor karlik IV darajasi (N90.3)',
  'uyda:5e': '5-e. Ikki tomonlama neyrosensor karlik / kar-soqovlik (N90.3)',
  'uyda:6a': '6-a. 3 yoki 4 darajali skolioz (M41)',
  'uyda:6b': '6-b. Ko‘krak qafasining girdobsimon deformatsiyasi (Q67.6)',
  'uyda:6v': '6-v. Ko‘krak qafasining qilsimon deformatsiyasi (Q67.7)',
  'uyda:6g': '6-g. 3 yoki 4 darajali kifoz (M40)',
  'uyda:6d': '6-d. Artrogripoz (Q74.3)',
  'uyda:6e': '6-e. Bolalar serebral falaji 3-4 daraja (G80)',
  'uyda:6j': '6-j. Tug‘ma va irsiy kasalliklar oqibatidagi ortopedik deformatsiyalar (Q90, Q96, Q98, Q87.1)',
  'uyda:6z': '6-z. Serebrovaskulyar kasalliklar oqibatlari + paraplegiya (I69.2 + G82.0 / G82.1)',
  'uyda:6i': '6-i. Spinal mushak atrofiyasi (G12)',
  'uyda:6k': '6-k. Mushaklarning birlamchi shikastlanishlari (G71)',
  'uyda:6l-para': '6-l. Paraplegiya va tetraplegiya (G82)',
  'uyda:6l-gemi': '6-l. Gemiplegiya (G81)',
  'uyda:6m': '6-m. Spina bifida (Q05)',
  'uyda:6n': '6-n. Osteomiyelit asoratlari (M86)',
  'uyda:6o': '6-o. Suyak skeletining tizim kasalliklari (Q77.4)',
  'uyda:6p': '6-p. Boldir va tovonning tug‘ma yo‘qligi (Q72.2)',
  'uyda:6r': '6-r. Tovon va tovon panjalarining tug‘ma yo‘qligi (Q72.3)',
  'uyda:6s': '6-s. Qo‘l panja va barmoq(larning) tug‘ma yo‘qligi (Q71.3)',
  'uyda:6t': '6-t. Bilak va qo‘l panjalarning tug‘ma yo‘qligi (Q71.2)',
  'uyda:6u': '6-u. Tovonning borligi holda son va boldir tug‘ma yo‘qligi (Q72.1)',
  'uyda:6f': '6-f. Qo‘l panjalarning borligi holda yelka va bilak suyaklari tug‘ma yo‘qligi (Q71.1)',
  'uyda:6x': '6-x. Aniqlanmagan oyoq-qo‘l tug‘ma anomaliyalari (Q74.9)',
};

export function getIllnessLabel(id?: string): string {
  if (!id) return '';
  return ILLNESS_LABELS[id] || id;
}
